version: '3.3'
services:
    ignite-node-1:
        image: apacheignite/ignite
        container_name: ignite-node-one
        ports:
            - "10800:10800"

    ignite-node-2:
        image: apacheignite/ignite
        container_name: ignite-node-sec
        ports:
             - "10900:10800"